import * as THREE from 'three';
import { DustAudioPlayer, type DustAudioStatus } from './DustAudioPlayer';
import { DustLightingDirector, type DustLightingStatus, type LightingStage } from './lighting/DustLightingDirector';
import { MOVEMENT_ACTIONS, MovementActionLab, type MovementGroup } from './lighting/MovementActionLab';
import { PhysicalLightingExecutor } from './lighting/PhysicalLightingExecutor';
// Generated by the Vite plugin in vite.config.ts from the binary gzip file.
// @ts-expect-error virtual module is provided by nocturneDustMidiPlugin.
import dustMidiBase64 from 'virtual:nocturne-dust-midi';
import sourcePart01 from './source/nocturne-stage-source-01.js?raw';
import sourcePart02 from './source/nocturne-stage-source-02.js?raw';
import sourcePart03 from './source/nocturne-stage-source-03.js?raw';
import sourcePart04 from './source/nocturne-stage-source-04.js?raw';
import sourcePart05 from './source/nocturne-stage-source-05.js?raw';
import sourcePart06 from './source/nocturne-stage-source-06.js?raw';
import sourcePart07 from './source/nocturne-stage-source-07.js?raw';

const SOURCE_LENGTH = 127_767;
const sourceParts = [sourcePart01, sourcePart02, sourcePart03, sourcePart04, sourcePart05, sourcePart06, sourcePart07];

declare global {
  interface Window {
    THREE: typeof THREE;
    stage?: LightingStage;
    stageReady?: Promise<LightingStage>;
    dustLighting?: DustLightingDirector;
    dustAudio?: DustAudioPlayer;
    physicalLighting?: PhysicalLightingExecutor;
    motionLab?: MovementActionLab;
  }
}

async function decodeSource(): Promise<string> {
  if (typeof DecompressionStream !== 'function') {
    throw new Error('当前浏览器不支持 DecompressionStream');
  }

  const base64 = sourceParts.map(extractChunk).join('');
  const raw = atob(base64);
  const bytes = new Uint8Array(raw.length);
  for (let index = 0; index < raw.length; index += 1) bytes[index] = raw.charCodeAt(index);

  const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));
  const source = await new Response(stream).text();
  if (source.length !== SOURCE_LENGTH) {
    throw new Error(`NOCTURNE source length mismatch: ${source.length}`);
  }
  return source;
}

function extractChunk(moduleSource: string): string {
  const match = moduleSource.match(/\.push\('([A-Za-z0-9+/=]+)'\);?/);
  if (!match) throw new Error('NOCTURNE source chunk is malformed');
  return match[1];
}

function patchForAssetViewer(source: string): string {
  if (!source.includes('          bindUI(app);')) {
    throw new Error('NOCTURNE UI bootstrap marker is missing');
  }
  return source.replace(
    '          bindUI(app);',
    '          // Venue Asset Library owns the thin overlay UI.',
  );
}

function formatTime(seconds: number): string {
  const value = Math.max(0, Math.floor(seconds));
  return `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`;
}

function updateDustStatus(status: DustLightingStatus): void {
  const statusNode = document.getElementById('dustStatus');
  if (statusNode) {
    statusNode.textContent = `${formatTime(status.time)} / ${formatTime(status.duration)} · bar ${status.bar + 1} · ${status.cue} · ${status.focus}`;
  }
  const playButton = document.getElementById('dustPlay') as HTMLButtonElement | null;
  if (playButton) {
    playButton.textContent = status.playing ? '暂停 Dust' : '播放 Dust';
    playButton.classList.toggle('active', status.playing);
  }
}

function updateAudioStatus(status: DustAudioStatus): void {
  const node = document.getElementById('audioStatus');
  if (!node) return;
  node.textContent = status.message;
  node.dataset.state = status.state;
}

function updateMotionStatus(message: string): void {
  const node = document.getElementById('motionStatus');
  if (node) node.textContent = message;
}

function bindDirectorToAudioClock(director: DustLightingDirector, audio: DustAudioPlayer): void {
  const internals = director as unknown as { currentTime: () => number };
  internals.currentTime = () => audio.currentTime;
}

function forceCurrentCue(director: DustLightingDirector, audio: DustAudioPlayer): void {
  const internals = director as unknown as { applyCueAtTime: (time: number, force?: boolean) => void };
  internals.applyCueAtTime(audio.currentTime, true);
}

function bindMovementControls(
  stage: LightingStage,
  director: DustLightingDirector,
  audio: DustAudioPlayer,
  physical: PhysicalLightingExecutor,
  lab: MovementActionLab,
): (restoreCue?: boolean) => void {
  const groupSelect = document.getElementById('motionGroup') as HTMLSelectElement | null;
  const actionsNode = document.getElementById('motionActionButtons');
  const restoreButton = document.getElementById('motionRestore') as HTMLButtonElement | null;
  let debugActive = false;
  let debugClockBase = 0;
  let debugClockStartedAt = 0;

  const enterDebug = (): void => {
    if (debugActive) return;
    if (director.isPlaying) director.pause();
    if (audio.isPlaying) audio.pause();
    stage.setDemo(false);
    stage.setPaused(false);
    stage.setStageMode('manual');
    lab.cancel();

    debugClockBase = audio.currentTime;
    debugClockStartedAt = performance.now() / 1000;
    physical.attachDirector({
      currentTime: () => debugClockBase + (performance.now() / 1000 - debugClockStartedAt),
    });
    debugActive = true;
    updateMotionStatus('动作调试模式 · Dust 已暂停');
  };

  const exitDebug = (restoreCue = true): void => {
    if (!debugActive) return;
    lab.cancel();
    physical.attachDirector(director);
    debugActive = false;
    if (restoreCue) {
      forceCurrentCue(director, audio);
      updateMotionStatus('已恢复 Dust 编排 · 当前暂停');
    } else {
      updateMotionStatus('动作调试待命');
    }
  };

  if (actionsNode) {
    actionsNode.replaceChildren();
    for (const action of MOVEMENT_ACTIONS) {
      const button = document.createElement('button');
      button.type = 'button';
      button.className = 'motion-action';
      button.textContent = action.label;
      button.title = action.note;
      button.addEventListener('click', () => {
        enterDebug();
        const group = (groupSelect?.value ?? 'rear') as MovementGroup;
        lab.run(action.id, group);
      });
      actionsNode.append(button);
    }
  }

  restoreButton?.addEventListener('click', () => exitDebug(true));
  return exitDebug;
}

function bindAssetControls(
  stage: LightingStage,
  director: DustLightingDirector,
  audio: DustAudioPlayer,
  exitMovementDebug: (restoreCue?: boolean) => void,
): void {
  const modeButtons = [...document.querySelectorAll<HTMLButtonElement>('[data-mode]')];
  for (const button of modeButtons) {
    button.addEventListener('click', () => {
      exitMovementDebug(false);
      director.stop(false);
      audio.stop();
      stage.setDemo(false);
      const mode = button.dataset.mode ?? 'nocturne';
      stage.setStageMode(mode);
      for (const candidate of modeButtons) candidate.classList.toggle('active', candidate === button);
    });
  }

  const dustPlay = document.getElementById('dustPlay') as HTMLButtonElement | null;
  dustPlay?.addEventListener('click', async () => {
    exitMovementDebug(true);
    for (const candidate of modeButtons) candidate.classList.remove('active');
    if (director.isPlaying) {
      director.pause();
      audio.pause();
      return;
    }

    dustPlay.disabled = true;
    try {
      const started = await audio.play();
      if (started) director.play();
    } finally {
      dustPlay.disabled = false;
    }
  });

  const dustRestart = document.getElementById('dustRestart') as HTMLButtonElement | null;
  dustRestart?.addEventListener('click', async () => {
    exitMovementDebug(false);
    for (const candidate of modeButtons) candidate.classList.remove('active');
    dustRestart.disabled = true;
    try {
      const started = await audio.restart(true);
      director.restart(started);
    } finally {
      dustRestart.disabled = false;
    }
  });

  const demoToggle = document.getElementById('demoToggle') as HTMLButtonElement | null;
  demoToggle?.addEventListener('click', () => {
    exitMovementDebug(false);
    director.stop(false);
    audio.stop();
    if (stage.demo) {
      stage.setDemo(false);
    } else {
      stage.setStageMode('nocturne');
      stage.setDemo(true);
    }
    if (demoToggle) demoToggle.textContent = stage.demo ? '停止演示' : '开始演示';
  });

  const pauseToggle = document.getElementById('pauseToggle') as HTMLButtonElement | null;
  pauseToggle?.addEventListener('click', () => {
    stage.setPaused(!stage.paused);
    if (pauseToggle) pauseToggle.textContent = stage.paused ? '继续动画' : '冻结动画';
  });
}

function inlineDustBytes(): Uint8Array {
  const raw = atob(dustMidiBase64);
  const bytes = new Uint8Array(raw.length);
  for (let index = 0; index < raw.length; index += 1) bytes[index] = raw.charCodeAt(index);
  return bytes;
}

async function createDustDirector(stage: LightingStage, dustBytes: Uint8Array): Promise<DustLightingDirector> {
  const nativeFetch = window.fetch.bind(window);
  const routedFetch: typeof window.fetch = (input, init) => {
    const requested = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
    if (requested.includes('dust.json.gz')) {
      return Promise.resolve(new Response(dustBytes.slice(), {
        status: 200,
        headers: {
          'Content-Type': 'application/gzip',
          'Content-Length': String(dustBytes.byteLength),
          'Cache-Control': 'no-store',
        },
      }));
    }
    return nativeFetch(input, init);
  };

  window.fetch = routedFetch;
  try {
    return await DustLightingDirector.create(stage, updateDustStatus);
  } finally {
    window.fetch = nativeFetch;
  }
}

async function start(): Promise<void> {
  window.THREE = THREE;
  const source = await decodeSource();
  Function(patchForAssetViewer(source))();
  if (!window.stageReady) throw new Error('NOCTURNE stageReady was not created');
  const stage = await window.stageReady;

  const dustBytes = inlineDustBytes();
  const audio = new DustAudioPlayer(dustBytes, updateAudioStatus);
  window.dustAudio = audio;

  const physical = new PhysicalLightingExecutor(stage);
  window.physicalLighting = physical;
  const director = await createDustDirector(stage, dustBytes);
  bindDirectorToAudioClock(director, audio);
  physical.attachDirector(director);
  window.dustLighting = director;

  const motionLab = new MovementActionLab(stage, physical, updateMotionStatus);
  window.motionLab = motionLab;
  const exitMovementDebug = bindMovementControls(stage, director, audio, physical, motionLab);
  bindAssetControls(stage, director, audio, exitMovementDebug);

  document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach((button) => button.classList.remove('active'));
  director.restart(false);
  void audio.prepare();
  updateMotionStatus('动作调试待命');
  document.getElementById('viewport')?.focus();
}

start().catch((error) => {
  console.error('[Venue Asset / NOCTURNE]', error);
  const note = document.getElementById('loadingNote');
  if (note) note.textContent = `场景未能启动：${error instanceof Error ? error.message : String(error)}`;
  const line = document.querySelector<HTMLElement>('.loading-line');
  if (line) line.style.display = 'none';
});
