import * as THREE from 'three';
import { DustAudioPlayer, type DustAudioStatus } from './DustAudioPlayer';
import { createDustReferenceShowPlan, decodeLegacyDustScore } from './lighting/v2/DustReferenceShow';
import { NocturneLightingAdapter, type LightingStage } from './lighting/v2/NocturneLightingAdapter';
import {
  DeterministicLightingRuntime,
  compileShowPlan,
  type RuntimeStatus,
} from './lighting/v2/ShowRuntime';
import type { CompiledShow, RigSnapshot, ShowPlan } from './lighting/v2/contracts';
// Generated by the Vite plugin in vite.config.ts from the binary gzip file.
// @ts-expect-error virtual module is provided by nocturneDustMidiPlugin.
import dustMidiBase64 from 'virtual:nocturne-dust-midi';
import sourcePart01 from './source/nocturne-stage-source-01.js?raw';
import sourcePart02 from './source/nocturne-stage-source-02.js?raw';
import sourcePart03 from './source/nocturne-stage-source-03.js?raw';
import sourcePart04 from './source/nocturne-stage-source-04.js?raw';
import sourcePart05 from './source/nocturne-stage-source-05.js?raw';
import sourcePart06 from './source/nocturne-stage-source-06.js?raw';
import sourcePart07 from './source/nocturne-stage-source-07.js?raw';

const SOURCE_LENGTH = 127_767;
const sourceParts = [sourcePart01, sourcePart02, sourcePart03, sourcePart04, sourcePart05, sourcePart06, sourcePart07];

declare global {
  interface Window {
    THREE: typeof THREE;
    stage?: LightingStage;
    stageReady?: Promise<LightingStage>;
    dustAudio?: DustAudioPlayer;
    nocturneLighting?: DeterministicLightingRuntime;
    nocturneRig?: RigSnapshot;
    nocturneShowPlan?: ShowPlan;
    nocturneCompiledShow?: CompiledShow;
  }
}

let audioRef: DustAudioPlayer | null = null;
let runtimeRef: DeterministicLightingRuntime | null = null;
let draggingSeek = false;

async function decodeSource(): Promise<string> {
  if (typeof DecompressionStream !== 'function') {
    throw new Error('当前浏览器不支持 DecompressionStream');
  }

  const base64 = sourceParts.map(extractChunk).join('');
  const raw = atob(base64);
  const bytes = new Uint8Array(raw.length);
  for (let index = 0; index < raw.length; index += 1) bytes[index] = raw.charCodeAt(index);

  const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));
  const source = await new Response(stream).text();
  if (source.length !== SOURCE_LENGTH) {
    throw new Error(`NOCTURNE source length mismatch: ${source.length}`);
  }
  return source;
}

function extractChunk(moduleSource: string): string {
  const match = moduleSource.match(/\.push\('([A-Za-z0-9+/=]+)'\);?/);
  if (!match) throw new Error('NOCTURNE source chunk is malformed');
  return match[1];
}

function patchForAssetViewer(source: string): string {
  if (!source.includes('          bindUI(app);')) {
    throw new Error('NOCTURNE UI bootstrap marker is missing');
  }
  return source.replace('          bindUI(app);', '          // Runtime V2 owns the thin playback UI.');
}

function inlineDustBytes(): Uint8Array {
  const raw = atob(dustMidiBase64);
  const bytes = new Uint8Array(raw.length);
  for (let index = 0; index < raw.length; index += 1) bytes[index] = raw.charCodeAt(index);
  return bytes;
}

function formatTime(seconds: number): string {
  const value = Math.max(0, Math.floor(seconds));
  return `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`;
}

function updateAudioStatus(status: DustAudioStatus): void {
  const node = document.getElementById('audioStatus');
  if (node) {
    node.textContent = status.message;
    node.dataset.state = status.state;
  }

  const play = document.getElementById('showPlay') as HTMLButtonElement | null;
  if (play) {
    play.textContent = status.state === 'playing' ? '暂停' : '播放';
    play.classList.toggle('active', status.state === 'playing');
  }

  const transportReady = status.state !== 'loading' && status.state !== 'error';
  const seek = document.getElementById('showSeek') as HTMLInputElement | null;
  if (seek) seek.disabled = !transportReady;
  for (const button of document.querySelectorAll<HTMLButtonElement>('[data-section-jump]')) {
    button.disabled = !transportReady;
  }
}

function updateRuntimeStatus(status: RuntimeStatus): void {
  const section = document.getElementById('runtimeSection');
  if (section) section.textContent = status.sectionLabel;
  const statusNode = document.getElementById('showStatus');
  if (statusNode) statusNode.textContent = `${formatTime(status.time)} / ${formatTime(status.duration)} · ${status.activeCueIds.length} cues`;
  const clock = document.getElementById('showClock');
  if (clock) clock.textContent = `${formatTime(status.time)} / ${formatTime(status.duration)}`;

  if (!draggingSeek) {
    const seek = document.getElementById('showSeek') as HTMLInputElement | null;
    if (seek) seek.value = String(status.time);
  }
}

function bindControls(audio: DustAudioPlayer, runtime: DeterministicLightingRuntime, plan: ShowPlan): void {
  const play = document.getElementById('showPlay') as HTMLButtonElement | null;
  const restart = document.getElementById('showRestart') as HTMLButtonElement | null;
  const seek = document.getElementById('showSeek') as HTMLInputElement | null;
  const determinism = document.getElementById('showDeterminism') as HTMLButtonElement | null;
  const sections = new Map(plan.sections.map((section) => [section.id, section]));

  if (seek) {
    seek.max = String(audio.songDuration || runtime.show.score.duration);
    seek.disabled = true;
    seek.addEventListener('pointerdown', () => { draggingSeek = true; });
    seek.addEventListener('pointerup', () => { draggingSeek = false; });
    seek.addEventListener('change', () => { draggingSeek = false; });
    seek.addEventListener('input', () => {
      const time = Number(seek.value);
      audio.seek(time);
      runtime.renderNow(time);
      const clock = document.getElementById('showClock');
      if (clock) clock.textContent = `${formatTime(time)} / ${formatTime(runtime.show.score.duration)}`;
    });
  }

  play?.addEventListener('click', async () => {
    play.disabled = true;
    try {
      if (audio.isPlaying) audio.pause();
      else await audio.play();
      runtime.renderNow();
    } finally {
      play.disabled = false;
    }
  });

  restart?.addEventListener('click', async () => {
    restart.disabled = true;
    try {
      await audio.restart(true);
      runtime.renderNow(0);
    } finally {
      restart.disabled = false;
    }
  });

  for (const button of document.querySelectorAll<HTMLButtonElement>('[data-section-jump]')) {
    button.addEventListener('click', () => {
      const target = sections.get(button.dataset.sectionJump ?? '');
      if (!target) return;
      audio.seek(target.startSeconds);
      runtime.renderNow(target.startSeconds);
    });
  }

  determinism?.addEventListener('click', () => {
    const time = audio.currentTime;
    const first = runtime.evaluateAt(time);
    const second = runtime.evaluateAt(time);
    const same = frameSignature(first) === frameSignature(second);
    determinism.textContent = same ? '同一时刻 = 同一帧 ✓' : '确定性检查失败';
    determinism.classList.toggle('ok', same);
    window.setTimeout(() => {
      determinism.textContent = '复算当前时刻';
      determinism.classList.remove('ok');
    }, 1800);
  });

  window.addEventListener('keydown', (event) => {
    if (event.code !== 'Space' || event.repeat || isFormTarget(event.target)) return;
    event.preventDefault();
    play?.click();
  });
}

function renderSectionButtons(plan: ShowPlan): void {
  const node = document.getElementById('sectionJumps');
  if (!node) return;
  node.replaceChildren();
  for (const section of plan.sections) {
    const button = document.createElement('button');
    button.type = 'button';
    button.disabled = true;
    button.dataset.sectionJump = section.id;
    button.textContent = section.label.split('·')[0]?.trim() || section.label;
    button.title = `${formatTime(section.startSeconds)} · ${section.intent}`;
    node.append(button);
  }
}

function renderDiagnostics(compiled: CompiledShow): void {
  const errors = compiled.diagnostics.filter((item) => item.severity === 'error');
  const warnings = compiled.diagnostics.filter((item) => item.severity === 'warning');
  const node = document.getElementById('runtimeDiagnostics');
  if (node) node.textContent = errors.length ? `${errors.length} errors` : warnings.length ? `${warnings.length} warnings` : 'PLAN COMPILED';
  if (compiled.diagnostics.length) console.table(compiled.diagnostics);
  if (errors.length) throw new Error(errors.map((error) => `${error.code}: ${error.message}`).join('\n'));
}

function frameSignature(frame: ReturnType<DeterministicLightingRuntime['evaluateAt']>): string {
  return JSON.stringify({
    section: frame.sectionId,
    cues: frame.activeCueIds,
    fixtures: [...frame.fixtures].map(([id, state]) => [
      id,
      Number(state.intensity.toFixed(6)),
      state.color,
      Number(state.pan.toFixed(5)),
      Number(state.tilt.toFixed(5)),
      Number(state.beamAngleDeg.toFixed(5)),
    ]),
  });
}

function isFormTarget(target: EventTarget | null): boolean {
  return target instanceof HTMLInputElement || target instanceof HTMLButtonElement || target instanceof HTMLSelectElement || target instanceof HTMLTextAreaElement;
}

async function start(): Promise<void> {
  window.THREE = THREE;
  const source = await decodeSource();
  Function(patchForAssetViewer(source))();
  if (!window.stageReady) throw new Error('NOCTURNE stageReady was not created');
  const stage = await window.stageReady;

  const dustBytes = inlineDustBytes();
  const score = await decodeLegacyDustScore(dustBytes);
  stage.setBPM?.(score.bpm);

  const audio = new DustAudioPlayer(dustBytes, updateAudioStatus);
  audioRef = audio;
  window.dustAudio = audio;

  const adapter = new NocturneLightingAdapter(stage);
  const rig = adapter.describeRig();
  const plan = createDustReferenceShowPlan(score, rig);
  const compiled = compileShowPlan(plan, rig, score);
  renderDiagnostics(compiled);

  const runtime = new DeterministicLightingRuntime(adapter, compiled, () => audio.currentTime, updateRuntimeStatus);
  runtimeRef = runtime;
  window.nocturneLighting = runtime;
  window.nocturneRig = rig;
  window.nocturneShowPlan = plan;
  window.nocturneCompiledShow = compiled;

  renderSectionButtons(plan);
  bindControls(audio, runtime, plan);
  runtime.start();
  updateRuntimeStatus({ time: 0, duration: score.duration, sectionId: plan.sections[0]?.id ?? null, sectionLabel: plan.sections[0]?.label ?? '序幕', activeCueIds: [] });

  const seek = document.getElementById('showSeek') as HTMLInputElement | null;
  if (seek) seek.max = String(score.duration);
  const planInfo = document.getElementById('planInfo');
  if (planInfo) planInfo.textContent = `${rig.fixtures.length} fixtures · ${plan.cues.length} cues · ${score.events.length} MIDI events`;

  const loading = document.getElementById('loading');
  if (loading) {
    loading.style.opacity = '0';
    window.setTimeout(() => loading.remove(), 650);
  }

  void audio.prepare();
  document.getElementById('viewport')?.focus();
}

window.addEventListener('beforeunload', () => {
  runtimeRef?.dispose();
  audioRef?.dispose();
});

start().catch((error) => {
  console.error('[Venue Asset / NOCTURNE Runtime V2]', error);
  const note = document.getElementById('loadingNote');
  if (note) note.textContent = `场景未能启动：${error instanceof Error ? error.message : String(error)}`;
  const line = document.querySelector<HTMLElement>('.loading-line');
  if (line) line.style.display = 'none';
});
