import assert from 'node:assert/strict';
import {ScreenSession} from '../src/screens/ScreenSession.ts';
const displays=new Map(),owners=new Set(),updates=new Map(),disposed=[];
const descriptors=['main','left','right'].map(id=>({id,width:10,height:3,pixelWidth:320,pixelHeight:100}));
const port={screens:descriptors,acquire(id){assert.ok(!owners.has(id));owners.add(id);return{present(surface){if(surface==='bad')throw Error('bad surface');displays.set(id,surface);},invalidate(){},release(){owners.delete(id);displays.delete(id);}};}};
const source=label=>({label,create(screen){return{surface:label,update:f=>{updates.set(screen.id,{...f});return true;},dispose:()=>disposed.push(label+':'+screen.id)};}});
const session=new ScreenSession(port);
await session.setContent(['main','left'],source('first'));
session.update(.05,{time:12.5,playing:true});assert.equal(updates.get('main').time,12.5);
session.update(.05,{time:2,playing:false});assert.equal(updates.get('left').time,2);assert.equal(updates.get('left').playing,false);
session.setOptions(['main'],{playing:false});session.update(.05,{time:20,playing:true});assert.equal(updates.get('main').time,2);assert.equal(updates.get('left').time,20);
session.setOptions(['main'],{playing:true});session.update(.05,{time:30,playing:true});assert.equal(updates.get('main').time,30);
await assert.rejects(()=>session.setContent(['main','right'],{label:'broken',create(screen){if(screen.id==='right')throw Error('load failed');return source('partial').create(screen);}}));
assert.equal(displays.get('main'),'first');assert.equal(displays.has('right'),false);assert.ok(disposed.includes('partial:main'));
await assert.rejects(()=>session.setContent(['main','left'],{label:'bad',create(screen){return {...source('rollback').create(screen),surface:screen.id==='left'?'bad':'new'};}}));assert.equal(displays.get('main'),'first');assert.equal(displays.get('left'),'first');
let finish;const late=session.setContent(['main'],{label:'late',create:()=>new Promise(resolve=>finish=resolve)});
await session.setContent(['main'],source('winner'));
finish(source('aborted').create(descriptors[0]));await assert.rejects(late,{name:'AbortError'});assert.equal(displays.get('main'),'winner');assert.ok(disposed.includes('aborted:main'));
let cancelLoad;const cancelled=session.setContent(['main'],{label:'cancel',create:()=>new Promise(resolve=>cancelLoad=resolve)});
session.cancelPending(['main']);cancelLoad(source('cancelled').create(descriptors[0]));await assert.rejects(cancelled,{name:'AbortError'});assert.equal(displays.get('main'),'winner');
await session.setContent(['right'],source('local'),{clock:'local'});session.update(.05,{time:123,playing:false});assert.ok(updates.get('right').time<1);assert.equal(updates.get('right').playing,true);
await session.setContent(['main'],{label:'runtime-error',create(){let calls=0;return{surface:'frame',update(){if(++calls>1)throw Error('draw failed');},dispose(){}};}});
session.update(.05,null);assert.match(session.status('main').error,/draw failed/);assert.equal(session.status('left').error,null);
assert.throws(()=>session.setOptions(['left'],{brightness:NaN}));assert.equal(session.status('left').options.brightness,.85);
let closePending;const pending=session.setContent(['left'],{label:'pending',create:()=>new Promise(resolve=>closePending=resolve)});session.dispose();session.dispose();closePending(source('closed').create(descriptors[1]));await assert.rejects(pending,{name:'AbortError'});assert.ok(disposed.includes('closed:left'));assert.equal(owners.size,0);
console.log('Screens: song/local clocks, pause, independent targets, atomic replacement, cancellation, rollback, runtime isolation and disposal passed.');
