import type { InstrumentOrbitCameraView } from '../CameraRegistry';

export type AtelierKeyboardViewName = 'whole' | 'lower' | 'upper' | 'pedals' | 'back';

export const ATELIER_KEYBOARD_VIEW_IDS: Record<AtelierKeyboardViewName, string> = {
  whole: 'keyboard.main:whole',
  lower: 'keyboard.main:lower',
  upper: 'keyboard.main:upper',
  pedals: 'keyboard.main:pedals',
  back: 'keyboard.main:back',
};

export const ATELIER_KEYBOARD_VIEWS: InstrumentOrbitCameraView[] = [
  {
    kind: 'instrument-orbit',
    id: ATELIER_KEYBOARD_VIEW_IDS.whole,
    label: 'Whole',
    instrumentId: 'keyboard.main',
    target: [0, 5.36, 0.15],
    yaw: 0.39,
    pitch: 0.425,
    height: 14.2,
    width: 16.4,
    fov: 34,
    near: 0.05,
    far: 160,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_KEYBOARD_VIEW_IDS.lower,
    label: 'Lower',
    instrumentId: 'keyboard.main',
    target: [0.05, 8.04, 0.30],
    yaw: 0.05,
    pitch: 0.32,
    height: 4.8,
    width: 14.9,
    fov: 34,
    near: 0.05,
    far: 160,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_KEYBOARD_VIEW_IDS.upper,
    label: 'Upper',
    instrumentId: 'keyboard.main',
    target: [0, 10.38, -0.73],
    yaw: 0.16,
    pitch: 0.64,
    height: 4.9,
    width: 11.9,
    fov: 34,
    near: 0.05,
    far: 160,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_KEYBOARD_VIEW_IDS.pedals,
    label: 'Pedals',
    instrumentId: 'keyboard.main',
    target: [0, 0.28, 2.45],
    yaw: 0.22,
    pitch: 0.65,
    height: 2.2,
    width: 3.5,
    fov: 34,
    near: 0.05,
    far: 160,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_KEYBOARD_VIEW_IDS.back,
    label: 'Back',
    instrumentId: 'keyboard.main',
    target: [0, 5.33, -0.15],
    yaw: Math.PI + 0.38,
    pitch: 0.25,
    height: 14.1,
    width: 16.4,
    fov: 34,
    near: 0.05,
    far: 160,
  },
];
