import type { InstrumentOrbitCameraView } from '../CameraRegistry';

export type AtelierViolinViewName = 'whole' | 'body' | 'neck' | 'head' | 'back';

export const ATELIER_VIOLIN_VIEW_IDS: Record<AtelierViolinViewName, string> = {
  whole: 'violin.main:whole',
  body: 'violin.main:body',
  neck: 'violin.main:neck',
  head: 'violin.main:head',
  back: 'violin.main:back',
};

export const ATELIER_VIOLIN_VIEWS: InstrumentOrbitCameraView[] = [
  {
    kind: 'instrument-orbit',
    id: ATELIER_VIOLIN_VIEW_IDS.whole,
    label: 'Whole',
    instrumentId: 'violin.main',
    target: [0.43, 1.45, 0.04],
    yaw: 0.22,
    pitch: 0.06,
    height: 8.30,
    width: 4.85,
    fov: 33,
    near: 0.035,
    far: 110,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_VIOLIN_VIEW_IDS.body,
    label: 'Body',
    instrumentId: 'violin.main',
    target: [0, -0.02, 0.14],
    yaw: 0.18,
    pitch: 0.07,
    height: 4.28,
    width: 3.1,
    fov: 33,
    near: 0.035,
    far: 110,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_VIOLIN_VIEW_IDS.neck,
    label: 'Neck',
    instrumentId: 'violin.main',
    target: [0, 2.18, 0.34],
    yaw: 0.06,
    pitch: 0.02,
    height: 3.75,
    width: 2.25,
    fov: 33,
    near: 0.035,
    far: 110,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_VIOLIN_VIEW_IDS.head,
    label: 'Head',
    instrumentId: 'violin.main',
    target: [0, 3.78, 0.26],
    yaw: 0.82,
    pitch: 0.045,
    height: 1.8,
    width: 1.82,
    fov: 33,
    near: 0.035,
    far: 110,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_VIOLIN_VIEW_IDS.back,
    label: 'Back',
    instrumentId: 'violin.main',
    target: [0, 1.21, 0],
    yaw: Math.PI + 0.32,
    pitch: 0.08,
    height: 7.67,
    width: 4.85,
    fov: 33,
    near: 0.035,
    far: 110,
  },
];
