import type { InstrumentOrbitCameraView } from '../CameraRegistry';

export type AtelierAcousticViewName = 'whole' | 'body' | 'neck' | 'head' | 'back';

export const ATELIER_ACOUSTIC_VIEW_IDS: Record<AtelierAcousticViewName, string> = {
  whole: 'acoustic.main:whole',
  body: 'acoustic.main:body',
  neck: 'acoustic.main:neck',
  head: 'acoustic.main:head',
  back: 'acoustic.main:back',
};

export const ATELIER_ACOUSTIC_VIEWS: InstrumentOrbitCameraView[] = [
  {
    kind: 'instrument-orbit',
    id: ATELIER_ACOUSTIC_VIEW_IDS.whole,
    label: 'Whole',
    instrumentId: 'acoustic.main',
    target: [0, 1.05, 0],
    yaw: 0.31,
    pitch: 0.09,
    height: 11.5,
    width: 6.2,
    fov: 32,
    near: 0.04,
    far: 120,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_ACOUSTIC_VIEW_IDS.body,
    label: 'Body',
    instrumentId: 'acoustic.main',
    target: [0, -1.23, 0.05],
    yaw: 0.18,
    pitch: 0.12,
    height: 5.8,
    width: 4.9,
    fov: 32,
    near: 0.04,
    far: 120,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_ACOUSTIC_VIEW_IDS.neck,
    label: 'Neck',
    instrumentId: 'acoustic.main',
    target: [0, 2.42, 0.56],
    yaw: 0.10,
    pitch: 0.055,
    height: 5.25,
    width: 2.55,
    fov: 32,
    near: 0.04,
    far: 120,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_ACOUSTIC_VIEW_IDS.head,
    label: 'Head',
    instrumentId: 'acoustic.main',
    target: [0, 4.63, 0.38],
    yaw: -0.24,
    pitch: 0.075,
    height: 3.2,
    width: 2.25,
    fov: 32,
    near: 0.04,
    far: 120,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_ACOUSTIC_VIEW_IDS.back,
    label: 'Back',
    instrumentId: 'acoustic.main',
    target: [0, 1.05, 0],
    yaw: Math.PI + 0.27,
    pitch: 0.08,
    height: 11.5,
    width: 6.2,
    fov: 32,
    near: 0.04,
    far: 120,
  },
];
