import type { InstrumentOrbitCameraView } from '../CameraRegistry';

export type AtelierElectricViewName = 'whole' | 'body' | 'neck' | 'head' | 'back';

export const ATELIER_ELECTRIC_VIEW_IDS: Record<AtelierElectricViewName, string> = {
  whole: 'electric.main:whole',
  body: 'electric.main:body',
  neck: 'electric.main:neck',
  head: 'electric.main:head',
  back: 'electric.main:back',
};

export const ATELIER_ELECTRIC_VIEWS: InstrumentOrbitCameraView[] = [
  {
    kind: 'instrument-orbit',
    id: ATELIER_ELECTRIC_VIEW_IDS.whole,
    label: 'Whole',
    instrumentId: 'electric.main',
    target: [0.05, 1.15, 0],
    yaw: -0.32,
    pitch: 0.07,
    height: 10.75,
    width: 5.25,
    fov: 33,
    near: 0.035,
    far: 110,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_ELECTRIC_VIEW_IDS.body,
    label: 'Body',
    instrumentId: 'electric.main',
    target: [0.12, -1.06, 0.08],
    yaw: -0.22,
    pitch: 0.09,
    height: 5.65,
    width: 4.7,
    fov: 33,
    near: 0.035,
    far: 110,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_ELECTRIC_VIEW_IDS.neck,
    label: 'Neck',
    instrumentId: 'electric.main',
    target: [0, 1.94, 0.29],
    yaw: -0.10,
    pitch: 0.035,
    height: 5.52,
    width: 2.6,
    fov: 33,
    near: 0.035,
    far: 110,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_ELECTRIC_VIEW_IDS.head,
    label: 'Head',
    instrumentId: 'electric.main',
    target: [0, 5.15, 0.16],
    yaw: -0.24,
    pitch: 0.07,
    height: 2.64,
    width: 2.6,
    fov: 33,
    near: 0.035,
    far: 110,
  },
  {
    kind: 'instrument-orbit',
    id: ATELIER_ELECTRIC_VIEW_IDS.back,
    label: 'Back',
    instrumentId: 'electric.main',
    target: [0.05, 1.15, 0],
    yaw: Math.PI + 0.28,
    pitch: 0.065,
    height: 10.75,
    width: 5.25,
    fov: 33,
    near: 0.035,
    far: 110,
  },
];
